name = "bookmarks-app"
pages_build_output_dir = "."

# Bind D1 Database
[[d1_databases]]
binding = "DB"
database_name = "bookmarks-db"
database_id = "fd177b20-b31f-4589-86d1-c0db0b4de9a3"

# Service Binding kết nối sang Worker WebSocket (bookmarks-ws)
[[services]]
binding = "WS_WORKER"
service = "bookmarks-ws"
